### ISSUE TITLE
2001_system_harfbuzz_graphite2.patch with ff53.0b9 gets link errors with ld.gold

### ISSUE THREAD

**Issue by zarniwhoop73** [karolgrudzinski/c2p-overlay#5]
Hi,

This might be irrelevant to you because your upstream has already solved it, or because you don't use gold, or you don't enable the option.

I normally hack on Beyond LinuxFromScratch (with upstream releases), and gentoo's patch(es) for system graphite2 and harfbuzz are attractive to me. With the changes for ff-53 (the requirement for rust) I wanted to see if I could still use the patches with a current beta, but I failed to find anything "official" for ff53. The closest I could find was your version. But it failed to link:

`/usr/bin/ld.gold: error: /scratch/working/firefox-53.0b9/firefox-build-dir/toolkit/library/../../gfx/thebes/gfxFontconfigFonts.o: requires dynamic R_X86_64_PC32 reloc against 'hb_glib_script_from_script' which may overflow at runtime; recompile with -fPIC
/usr/bin/ld.gold: error: read-only segment has dynamic relocations
/usr/bin/ld.gold: error: hidden symbol 'hb_glib_script_from_script' is not defined locally
collect2: error: ld returned 1 exit status
make[5]: *** [/scratch/working/firefox-53.0b9/config/rules.mk:803: libxul.so] Error 1`

Following the comments in post 22 of [https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1306543] I guess that axs has already fixed this "upstream".

The attached diff against the 2001 patch fixed it for me (i.e. adding harfbuzz/hb-glib.h at the start of the config/system-headers additions for harfbuzz - github is somewhat unfriendly for attaching patches) :

[ff53-gold-fixes.txt](https://github.com/karolgrudzinski/c2p-overlay/files/923170/ff53-gold-fixes.txt)

**Comment by karolgrudzinski** [comment]
I checked it and after running `ebuild firefox-53.0_beta9.ebuild prepare` (unpacking + patching) I can see that I have those lines in config/system-headers at lines 1272-1278:

> graphite2/Segment.h
#endif
#if MOZ_SYSTEM_HARFBUZZ==1
harfbuzz/hb-glib.h
harfbuzz/hb-ot.h
harfbuzz/hb.h
#endif

And this lines were added by patch ` 2001_system_harfbuzz.patch` from original gentoo patchset (firefox-52.0-patches-08.tar.xz from https://dev.gentoo.org/~axs/mozilla/patchsets/).
Lines 28-52 from that file:

> diff --git a/config/system-headers b/config/system-headers
--- a/config/system-headers
+++ b/config/system-headers
@@ -1260,16 +1260,21 @@ zlib.h
 #ifdef MOZ_ENABLE_STARTUP_NOTIFICATION
 libsn/sn.h
 libsn/sn-common.h
 libsn/sn-launchee.h
 libsn/sn-launcher.h
 libsn/sn-monitor.h
 libsn/sn-util.h
 #endif
+#if MOZ_SYSTEM_HARFBUZZ==1
+harfbuzz/hb-glib.h
+harfbuzz/hb-ot.h
+harfbuzz/hb.h
+#endif
 #if MOZ_SYSTEM_HUNSPELL==1
 hunspell.hxx
 #endif
 #if MOZ_SYSTEM_BZ2==1
 bzlib.h
 #endif
 #ifdef MOZ_ENABLE_GIO
 gio/gio.h

So I don't have anything to fix because all gentoo patches (mine and official from axs) include upstream fixes.

**Comment by karolgrudzinski** [comment]
Oh, and file `2001_system_harfbuzz_graphite2.patch` was created on 25th January and was meant for old version and it isn't used by any ebuild anymore. I should remove it from my repository.
