### ISSUE TITLE
Build bug in Firefox 53

### ISSUE THREAD

**Issue by jorgicio** [karolgrudzinski/c2p-overlay#7]
Hi! First of all, thanks for the bump of Firefox 53. However, it fails at build, maybe because of some hunspell issues. As a suggestion, I rather wait for the official patches for that version, but I'm not sure if does it fix that issue.
Anyways, there goes the log. Thanks.
[emerge-info.txt](https://github.com/karolgrudzinski/c2p-overlay/files/934924/emerge-info.txt)

[firefox-53-build.txt](https://github.com/karolgrudzinski/c2p-overlay/files/934921/firefox-53-build.txt)

**Comment by jorgicio** [comment]
Or maybe you may consider this patch you forgot in the Portage tree:

https://gitweb.gentoo.org/repo/gentoo.git/tree/www-client/firefox/files/musl_drop_hunspell_alloc_hooks.patch

**Comment by karolgrudzinski** [comment]
Firefox installed fine for me but I have `system-harfbuzz` USE flag enabled, so it seems that this bug only exists when you use hunspell/harfbuzz bundled in firefox.
I think that this patch will fix this issue.
Thanks

**Comment by jorgicio** [comment]
You're welcome, but now I applied this patch, tried again, and still fails at build. Please check this new log. Thanks.
[firefox-53-build.txt](https://github.com/karolgrudzinski/c2p-overlay/files/935469/firefox-53-build.txt)

**Comment by jorgicio** [comment]
Note: Now I tried installing with system-harfbuzz, but I got the same error. What hunspell version are you using? I'm with the stable in Gentoo, the 1.3.3.

**Comment by karolgrudzinski** [comment]
I use most recent version of hunspell - 1.6.1-r1.
I completely forgot that I also have had problem compiling firefox with version 1.3.3 of hunspell. This was long time ago when I used libreoffice-bin which depend on that old version of hunspell. Installing firefox was a little tricky - I have to install latest hunspell, compile firefox, and downgrade hunspell becuase libreoffice wouldn't work. This was very frustrating so I made my own ebuild for libreoffice-bin which uses official RPMs instead of gentoo provided binary so I could update hunspell for good. It was somewhere in mid-2016 so I completely forgot this horror story.

**Comment by jorgicio** [comment]
Ok, I got it, I did something similar with Perl, so I understood your idea. the -bin package was just released in the Gentoo tree, and there's a stabilization request for hunspell to the 1.6.1 version (for a while, stable in hppa only).
I wish this may be ready soon :D 
https://bugs.gentoo.org/show_bug.cgi?id=615478

**Comment by karolgrudzinski** [comment]
Firefox 53.0 was added to mozilla-overlay with official patchset (53.0-patches-01). I compared this version with 52.0-patches-08 and I can see both patchsets are almost the same so sadly there isn't fix for hunspell yet.

**Comment by jorgicio** [comment]
Don't worry, hunspell may be stabilized soon, so we may expect that.

**Comment by karolgrudzinski** [comment]
I have nothing to worry about because I have a working firefox 53.0 and you don't (yet) :P. I only worry that my devoted overlay users have to wait a little longer because it takes so much time to have anything stabilized on gentoo.
Until today I wasn't aware that the last version considered stable in gentoo is 45.8.0. So ordinary desktop user has to use ~ arch for browser and its dependencies to have modern and secure web experience. I use gentoo since 2004 and I'm on unstable (~) arch almost from the beginning and I can can count on one hand the number of times I had a problem with it. I think that stable branch on desktop creates more problems than it fixes and this firefox situation is good example of that.

**Comment by karolgrudzinski** [comment]
Firefox in Mozilla Overlay now depends on >=app-text/hunspell-1.5.4 so I will make the same change which should definitely solve this issue.

**Comment by jorgicio** [comment]
Thanks, finally I had to "unmask" all its dependencies (libreoffice, hunspell itself and glew) and today all their (almost) latest versions went stable, so I finally could (re)build Firefox 53 fine.
Thank you
